id = "B"

params_path = "./tests/constraints.hpp"
sample_path = "./rime-out/tests"
ignore_samples = []

[[statements]]
path = "./statement/statement.md"
lang = "ja"
markdown_extensions = ["md_in_html", "tables", "fenced_code"]

[constraints]
MIN_A = 0
MAX_A = 100000
MIN_B = 0
MAX_B = 100000

[mofe]
problem_id = 321 # MOFE 上での問題 ID
difficulty = "Milk" # 問題の難易度、 "Milk", "Assam", "Benihuki", "Ceylon", "Darjeeling", "Earlgray", "Flavor", "ผักชี" から選ぶ
execution_time_limit = 2000 # 実行時間制限 (ms)
submission_limit_1 = 5 # 1 回前の提出から何秒間隔を開ける必要があるか
submission_limit_2 = 60 # 2 回前の提出から何秒間隔を開ける必要があるか

[[mofe.testcase_sets]]
name = "sample"
regex = "00_sample_\\d+" # sample のテストケースの名前にマッチする正規表現
points = 0 # sample ケースの配点
aggregate_type = "all"

[[mofe.testcase_sets]]
name = "all"
regex = "." # all のテストケースの名前にマッチする正規表現
points = 100 # all ケースの配点
aggregate_type = "all"
