// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int MIN_A = 0;
const long long int MAX_A = 100000;
const long long int MIN_B = 0;
const long long int MAX_B = 100000;
