name: Run test and upload testcases to MOFE

on:
  push:
    paths-ignore:
    - '**.md'
    - 'docs/**'

jobs:
  Rime-and-upload-testcases:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tuatmcc/sakumon-image:amd64
      volumes:
        - /github/workspace:/root/app
    permissions:
      contents: read
      packages: read
      attestations: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Working Directory
        run: cd /root/app

      - name: Generate constraints.hpp
        run: ss-manager run -c

      - name: Rime clean
        run: rime clean

      - name: Rime test
        run: rime test --keep_going

      - name: Embed samples and constraints into statements
        run: ss-manager run -o md

      - name: Upload testcases to MOFE
        uses: Ryohei222/mofe-upload-action
        with:
          mofe_username: ${{ vars.MOFE_USERNAME }}
          mofe_password: ${{ secrets.MOFE_PASSWORD }}
          upload_statement: true
          force_upload_statement: true
          upload_testcases: true
          use_debug_logging: true